name: Retrieve commit info
description: Retrieve commit info
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [[ "$GITHUB_REF_NAME" != "master" && "$GITHUB_REF_NAME" != "main" ]]; then
          SAFE_BRANCH_NAME=$(echo "$GITHUB_REF_NAME" | tr '/' '-')
          SAFE_BRANCH_NAME=$(echo "$SAFE_BRANCH_NAME" | sed 's/[^a-zA-Z0-9._-]//g')
          BRANCH_SUFFIX="-$SAFE_BRANCH_NAME"
        else
          BRANCH_SUFFIX=""
        fi
        echo "BRANCH_SUFFIX=$BRANCH_SUFFIX" >> $GITHUB_ENV
        
        COMMIT_NUMBER=$(git rev-list HEAD --count)
        echo "COMMIT_NUMBER=$COMMIT_NUMBER" >> $GITHUB_ENV
        
        SHA_7=${GITHUB_SHA::7}
        echo "SHA_7=$SHA_7" >> $GITHUB_ENV
        
        REVISION="1.${COMMIT_NUMBER}-${SHA_7}${BRANCH_SUFFIX}"
        echo "REVISION=$REVISION" >> $GITHUB_ENV
