name: Erlang build
on:
  workflow_call:

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: valitydev/action-setup-thrift@v0.0.6
        with:
          thrift-version: '0.14.2.1'

      - uses: erlef/setup-beam@v1.20
        id: beam
        with:
          otp-version: '24'
          rebar3-version: '3.18'

      - name: Restore PLT cache
        uses: actions/cache@v4
        id: plt-cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            _build/default/rebar3_*_plt

      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 dialyzer
