name: Maven Deploy Package

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "21"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
    secrets:
      server-username:
        required: true
      server-password:
        required: true
      deploy-secret-key:
        required: true
      deploy-secret-key-password:
        required: true
      mm-webhook-url:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Retrieve commit info
        id: commit_info
        uses: ./.github/actions/commit-info

      - name: Deploy package
        uses: valitydev/action-deploy-jdk-package@v1.0.20
        with:
          jdk-version: ${{ inputs.java-version }}
          jdk-distribution: ${{ inputs.java-distribution }}
          server-username: ${{ secrets.server-username }}
          server-password: ${{ secrets.server-password }}
          deploy-secret-key: ${{ secrets.deploy-secret-key }}
          deploy-secret-key-password: ${{ secrets.deploy-secret-key-password }}
          maven-args: '-Dcommit.number=${{ env.COMMIT_NUMBER }} -Drevision=${{ env.REVISION }}'

      - name: Mattermost Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""

  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - name: Maven Verify
        run: mvn --batch-mode clean verify

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
